# Generated by Django 2.1.1 on 2018-10-23 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_auto_20181022_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
