# Generated by Django 2.1.1 on 2018-10-18 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_auto_20181018_0511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charge',
            name='billing_profile',
        ),
        migrations.DeleteModel(
            name='Charge',
        ),
    ]
