# Generated by Django 2.1.1 on 2018-10-18 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_auto_20181018_0542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='active',
        ),
        migrations.RemoveField(
            model_name='card',
            name='timestamp',
        ),
    ]
