# Generated by Django 2.1.1 on 2018-10-19 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
