# Generated by Django 2.1.1 on 2018-10-14 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productviewed',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Product Viewed', 'verbose_name_plural': 'Products Viewed'},
        ),
    ]
