# Generated by Django 2.1.1 on 2018-10-22 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20181022_2157'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RenameField(
            model_name='guestemail',
            old_name='update',
            new_name='updated',
        ),
    ]
