# Generated by Django 2.1.1 on 2018-10-22 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_user_full_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
