# Generated by Django 2.1.1 on 2018-10-06 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.SlugField(blank=True, default='abc', unique=True),
        ),
    ]
