# Generated by Django 2.1.1 on 2018-10-27 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20181027_0626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='description1',
        ),
        migrations.AddField(
            model_name='product',
            name='description2',
            field=models.CharField(default='NONE', max_length=300),
            preserve_default=False,
        ),
    ]
