# Generated by Django 2.1.1 on 2018-10-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20181027_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description1',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='product',
            name='description2',
            field=models.CharField(max_length=400),
        ),
    ]
